import React, { useState } from 'react';
import { PROJECT_TYPES, EXPERIENCE_LEVELS, STACK_RECOMMENDATIONS } from '../data/stacks';
import { TOOLS } from '../data/tools';
import { Tool, StackRecommendation } from '../types';
import { Flame, Copy, Check, ExternalLink, Layers, Cpu, Database, Shield, Server, Rocket, BarChart2 } from 'lucide-react';

interface StackGeneratorProps {
  onSelectTool: (tool: Tool) => void;
}

export const StackGenerator: React.FC<StackGeneratorProps> = ({ onSelectTool }) => {
  const [selectedType, setSelectedType] = useState<string>('AI SaaS');
  const [selectedExperience, setSelectedExperience] = useState<'Beginner' | 'Intermediate' | 'Advanced'>('Beginner');
  const [copied, setCopied] = useState(false);

  // Retrieve recommendation or fallback to AI SaaS
  const currentStack: StackRecommendation =
    STACK_RECOMMENDATIONS[selectedType]?.[selectedExperience] ||
    STACK_RECOMMENDATIONS['AI SaaS']['Beginner'];

  const suggestedTools = currentStack.suggestedToolIds
    .map((id) => TOOLS.find((t) => t.id === id))
    .filter(Boolean) as Tool[];

  const handleCopyMarkdown = () => {
    const md = `### 🚀 Hackathon Project Stack: ${currentStack.projectType} (${currentStack.experience})

- **Frontend**: ${currentStack.frontend}
- **AI / Inference**: ${currentStack.aiModel}
- **Database / Vector**: ${currentStack.database}
- **Authentication**: ${currentStack.auth}
- **Backend Architecture**: ${currentStack.backend}
- **Deployment & Cloud**: ${currentStack.deployment}
- **Analytics & Observability**: ${currentStack.analytics}

> *Rationale*: ${currentStack.rationale}
*Generated by AI Hackathon Toolkit*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleOpenAllTabs = () => {
    suggestedTools.forEach((tool) => {
      window.open(tool.url, '_blank', 'noopener,noreferrer');
    });
  };

  const stackRows = [
    { label: 'Frontend', value: currentStack.frontend, icon: Layers, color: 'text-cyan-600 dark:text-cyan-400' },
    { label: 'AI Inference', value: currentStack.aiModel, icon: Cpu, color: 'text-emerald-600 dark:text-emerald-400' },
    { label: 'Database & Vectors', value: currentStack.database, icon: Database, color: 'text-purple-600 dark:text-purple-400' },
    { label: 'Authentication', value: currentStack.auth, icon: Shield, color: 'text-amber-600 dark:text-yellow-400' },
    { label: 'Backend Architecture', value: currentStack.backend, icon: Server, color: 'text-blue-600 dark:text-blue-400' },
    { label: 'Cloud Deployment', value: currentStack.deployment, icon: Rocket, color: 'text-rose-600 dark:text-rose-400' },
    { label: 'Telemetry & Analytics', value: currentStack.analytics, icon: BarChart2, color: 'text-indigo-600 dark:text-indigo-400' },
  ];

  return (
    <section id="stack-generator" className="py-16 sm:py-20 border-b border-gray-200 dark:border-white/10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="flex flex-col items-center text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-amber-500/30 bg-amber-500/10 text-amber-600 dark:text-amber-400 text-xs font-mono mb-3">
            <Flame className="w-3.5 h-3.5" />
            <span>ARCHITECTURAL_ENGINE // STACK_BUILDER</span>
          </div>
          <h2 className="text-3xl sm:text-4xl font-extrabold font-mono text-slate-900 dark:text-white tracking-tight mb-4">
            Build My Hackathon Stack
          </h2>
          <p className="text-sm sm:text-base text-slate-600 dark:text-gray-400 max-w-2xl font-sans">
            Select your hackathon project format and team experience level. Get an optimized, zero-friction developer stack with instant markdown export for your submission.
          </p>
        </div>

        {/* Configuration Controls */}
        <div className="p-6 sm:p-8 rounded-3xl border border-gray-200 dark:border-white/15 bg-white dark:bg-[#0d121d] shadow-md dark:shadow-[0_0_35px_rgba(0,0,0,0.4)] mb-8">
          <div className="space-y-6">
            {/* Step 1: Project Type Selection */}
            <div>
              <label className="block text-xs font-mono text-emerald-600 dark:text-emerald-400 font-semibold uppercase tracking-wider mb-3">
                01 // Select Project Architecture
              </label>
              <div className="flex flex-wrap gap-2">
                {PROJECT_TYPES.map((type) => {
                  const isSelected = selectedType === type;
                  return (
                    <button
                      key={type}
                      onClick={() => setSelectedType(type)}
                      className={`px-3.5 py-2 rounded-xl text-xs font-mono transition-all duration-200 border ${
                        isSelected
                          ? 'bg-emerald-500/20 border-emerald-500/80 text-emerald-800 dark:text-emerald-300 font-bold shadow-[0_0_12px_rgba(0,255,102,0.2)]'
                          : 'bg-gray-100 dark:bg-[#121724] border-gray-200 dark:border-white/10 text-slate-700 dark:text-gray-400 hover:text-slate-950 dark:hover:text-white hover:bg-gray-200 dark:hover:bg-white/5'
                      }`}
                    >
                      {type}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Step 2: Experience Level Selection */}
            <div>
              <label className="block text-xs font-mono text-cyan-600 dark:text-cyan-400 font-semibold uppercase tracking-wider mb-3">
                02 // Select Team Experience Level
              </label>
              <div className="flex flex-wrap gap-2.5">
                {EXPERIENCE_LEVELS.map((level) => {
                  const isSelected = selectedExperience === level;
                  return (
                    <button
                      key={level}
                      onClick={() => setSelectedExperience(level)}
                      className={`px-4 py-2 rounded-xl text-xs font-mono transition-all duration-200 border ${
                        isSelected
                          ? 'bg-cyan-500/20 border-cyan-500/80 text-cyan-800 dark:text-cyan-300 font-bold shadow-[0_0_12px_rgba(0,229,255,0.2)]'
                          : 'bg-gray-100 dark:bg-[#121724] border-gray-200 dark:border-white/10 text-slate-700 dark:text-gray-400 hover:text-slate-950 dark:hover:text-white hover:bg-gray-200 dark:hover:bg-white/5'
                      }`}
                    >
                      {level}
                    </button>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        {/* Generated Output Blueprint */}
        <div className="p-6 sm:p-8 rounded-3xl border border-emerald-500/30 bg-emerald-50/30 dark:bg-[#090d16] shadow-md dark:shadow-[0_0_30px_rgba(0,255,102,0.08)]">
          {/* Blueprint Header */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6 pb-4 border-b border-gray-200 dark:border-white/10">
            <div>
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-mono text-emerald-600 dark:text-emerald-400 uppercase tracking-wider font-semibold">
                  GENERATED ARCHITECTURE //
                </span>
                <span className="font-mono text-xs px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border border-emerald-500/20">
                  {selectedType}
                </span>
                <span className="font-mono text-xs px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-700 dark:text-cyan-300 border border-cyan-500/20">
                  {selectedExperience} Level
                </span>
              </div>
              <p className="text-xs text-slate-600 dark:text-gray-400 font-sans">
                {currentStack.rationale}
              </p>
            </div>

            {/* Quick Actions */}
            <div className="flex items-center gap-2.5 flex-shrink-0">
              <button
                onClick={handleCopyMarkdown}
                className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl font-mono text-xs font-semibold bg-white dark:bg-white/10 hover:bg-gray-100 dark:hover:bg-white/15 text-slate-800 dark:text-white border border-gray-300 dark:border-white/15 shadow-sm dark:shadow-none transition-all"
                title="Copy markdown block for README or Devpost"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" />
                    <span className="text-emerald-600 dark:text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5 text-gray-500 dark:text-gray-400" />
                    <span>Copy Markdown</span>
                  </>
                )}
              </button>

              <button
                onClick={handleOpenAllTabs}
                className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl font-mono text-xs font-semibold bg-emerald-500 hover:bg-emerald-400 text-black shadow-[0_0_15px_rgba(0,255,102,0.25)] transition-all"
                title="Open all tools in new browser tabs"
              >
                <ExternalLink className="w-3.5 h-3.5" />
                <span>Open All Tools</span>
              </button>
            </div>
          </div>

          {/* Stack Layer Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3.5 mb-8">
            {stackRows.map((row) => {
              const Icon = row.icon;
              return (
                <div
                  key={row.label}
                  className="p-4 rounded-2xl border border-gray-200 dark:border-white/10 bg-white dark:bg-[#101624]/80 flex items-start gap-3.5 shadow-sm dark:shadow-none"
                >
                  <div className="p-2 rounded-xl bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 flex-shrink-0">
                    <Icon className={`w-4 h-4 ${row.color}`} />
                  </div>
                  <div>
                    <span className="block text-[11px] font-mono text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      {row.label}
                    </span>
                    <span className="font-bold text-sm text-slate-900 dark:text-white font-mono">
                      {row.value}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Quick-Inspect Tools for This Stack */}
          <div>
            <span className="text-xs font-mono text-gray-500 dark:text-gray-400 uppercase tracking-wider block mb-3">
              Direct Quick Links for this Stack:
            </span>
            <div className="flex flex-wrap gap-2.5">
              {suggestedTools.map((tool) => (
                <button
                  key={tool.id}
                  onClick={() => onSelectTool(tool)}
                  className="flex items-center gap-2 px-3 py-1.5 rounded-xl border border-gray-200 dark:border-white/10 bg-white dark:bg-[#131926] hover:border-emerald-500/40 text-xs font-mono text-slate-700 dark:text-gray-300 hover:text-slate-950 dark:hover:text-white shadow-sm dark:shadow-none transition-colors"
                >
                  <img
                    src={`https://www.google.com/s2/favicons?domain=${new URL(tool.url).hostname}&sz=32`}
                    alt=""
                    className="w-3.5 h-3.5 object-contain"
                  />
                  <span>{tool.name}</span>
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
